export enum Device {
    SAMSUNG_GALAXY_NOTE8,
    SAMSUNG_GALAXY_S5,

    HTC_ONE,

    APPLE_IPAD_MINI,
    APPLE_IPHONE_5S,
    APPLE_IPHONE_8,
    APPLE_IPHONE_8PLUS,
    APPLE_IPHONE_X,
    APPLE_MACBOOK_PRO,

    GOOGLE_NEXUS_5
}